FROM evindunn/jenkins-worker:ubuntu-1804

USER root

RUN apt-get install -y gcc
RUN apt-get install -y wget bzip2 ca-certificates

RUN apt-get install -y x11-apps
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglu1-mesa-dev

RUN echo 'export PATH=/var/jenkins/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /var/jenkins/conda && \
    rm ~/miniconda.sh
ENV PATH /opt/conda/bin:$PATH

USER jenkins
