FROM evindunn/jenkins-worker:fedora-25

USER root

RUN dnf install -y gcc-c++
RUN dnf install -y wget bzip2 ca-certificates
RUN dnf install -y which

RUN dnf install -y xorg-x11-apps
RUN dnf install -y mesa-libGL
RUN dnf install -y mesa-libGLU-devel

RUN echo 'export PATH=/var/jenkins/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /var/jenkins/conda && \
    rm ~/miniconda.sh
ENV PATH /opt/conda/bin:$PATH

USER jenkins
