FROM evindunn/jenkins-worker:centos-7

USER root

RUN yum install -y gcc-c++
RUN yum install -y wget bzip2 ca-certificates
RUN yum install -y which

RUN yum install -y xorg-x11-apps
RUN yum install -y mesa-libGL
RUN yum install -y mesa-libGLU-devel

USER jenkins
