FROM evindunn/jenkins-worker:fedora-25

ENV CONDA_HOME /home/jenkins/conda
ENV PATH $CONDA_HOME:$PATH

USER root

RUN dnf install -y gcc-c++
RUN dnf install -y bzip2 ca-certificates
RUN dnf install -y which

RUN dnf install -y xorg-x11-apps
RUN dnf install -y mesa-libGL
RUN dnf install -y mesa-libGLU-devel

RUN curl -o ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
RUN /bin/bash ~/miniconda.sh -b -p $CONDA_HOME
RUN rm ~/miniconda.sh
RUN chown -R jenkins:jenkins $CONDA_HOME

USER jenkins
