FROM evindunn/jenkins-worker:debian-9

ENV CONDA_HOME /home/jenkins/conda
ENV PATH $CONDA_HOME:$PATH

USER root

RUN apt-get install -y gcc
RUN apt-get install -y bzip2 ca-certificates

RUN apt-get install -y x11-apps
RUN apt-get install -y libgl1-mesa-glx
RUN apt-get install -y libglu1-mesa-dev

RUN curl -o ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
RUN /bin/bash ~/miniconda.sh -b -p $CONDA_HOME
RUN rm ~/miniconda.sh
RUN chown -R jenkins:jenkins $CONDA_HOME

USER jenkins
